/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary-container": "#916a07",
        "on-error-container": "#93000a",
        "tertiary": "#735300",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faf2ea",
        "on-primary": "#ffffff",
        "surface-bright": "#fff8f2",
        "secondary-container": "#fe8760",
        "on-primary-fixed": "#171e00",
        "on-primary-container": "#f0fcc4",
        "background": "#fff8f2",
        "primary-fixed": "#dde8b1",
        "surface-variant": "#e8e1d9",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb59d",
        "surface": "#fff8f2",
        "on-tertiary-container": "#fff4e8",
        "on-secondary-fixed": "#390b00",
        "primary-container": "#6b7548",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#46483d",
        "outline-variant": "#c7c7b9",
        "inverse-primary": "#c1cc97",
        "surface-tint": "#596337",
        "on-secondary-container": "#732101",
        "primary-fixed-dim": "#c1cc97",
        "secondary": "#a0401f",
        "outline": "#77786c",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-background": "#1e1b17",
        "surface-container": "#f4ede5",
        "tertiary-fixed": "#ffdea4",
        "inverse-on-surface": "#f7f0e7",
        "secondary-fixed": "#ffdbd0",
        "surface-container-highest": "#e8e1d9",
        "on-surface": "#1e1b17",
        "on-secondary-fixed-variant": "#802a08",
        "on-tertiary-fixed": "#261900",
        "surface-container-high": "#eee7df",
        "surface-dim": "#e0d9d1",
        "tertiary-fixed-dim": "#f0bf5c",
        "error-container": "#ffdad6",
        "inverse-surface": "#33302b",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#414b22",
        "primary": "#535c32",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        sans: ["'IBM Plex Sans'", "sans-serif"],
        headline: ["'Space Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
    },
  },
  plugins: [],
};
